Pomegranate Markov Model explainer


In [ ]:

import seaborn; seaborn.set_style('whitegrid')
import torch


In [3]:
from pomegranate.markov_chain import MarkovChain

model = MarkovChain(k=3)

In [4]:
X = torch.tensor([[[1], [0], [0], [1]],
                  [[0], [1], [0], [0]],
                  [[0], [0], [0], [0]],
                  [[0], [0], [0], [1]],
                  [[0], [1], [1], [0]]])

model.fit(X)

MarkovChain()

In [5]:
model.distributions[0].probs[0]

tensor([0.8000, 0.2000])

In [6]:
model.distributions[1].probs[0]

Parameter containing:
tensor([[0.5000, 0.5000],
        [1.0000, 0.0000]])

In [7]:
model.distributions[2].probs[0]

Parameter containing:
tensor([[[1.0000, 0.0000],
         [0.5000, 0.5000]],

        [[1.0000, 0.0000],
         [0.5000, 0.5000]]])

In [8]:
model.probability(X)

tensor([0.2000, 0.2000, 0.2000, 0.2000, 0.2000])

In [9]:
model.log_probability(X)


tensor([-1.6094, -1.6094, -1.6094, -1.6094, -1.6094])

In [10]:
X = torch.randint(2, size=(30, 8, 1))

model.summarize(X[:10])
model.summarize(X[10:])
model.from_summaries()

In [11]:
model.distributions[0].probs

Parameter containing:
tensor([[0.4667, 0.5333]])